CREATE TABLE IF NOT EXISTS categories
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT categories_pk PRIMARY KEY,
    name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT users_pk PRIMARY KEY,
    name varchar NOT NULL,
    email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS locations
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT locations_pk PRIMARY KEY,
    lat double PRECISION NOT NULL,
    lon double PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT compilations_pk PRIMARY KEY,
    pinned boolean,
    title varchar
);

CREATE TABLE IF NOT EXISTS events
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT events_pk PRIMARY KEY,
    annotation varchar NOT NULL,
    category_id bigint NOT NULL CONSTRAINT events_categories_id_fk REFERENCES categories,
    confirmed_requests bigint,
    created_on timestamp,
    description varchar,
    event_date timestamp NOT NULL,
    initiator_id bigint NOT NULL CONSTRAINT events_users_id_fk REFERENCES users,
    location_id bigint NOT NULL CONSTRAINT events_locations_id_fk REFERENCES locations,
    paid boolean NOT NULL,
    participant_limit integer,
    published_on timestamp,
    request_moderation boolean,
    state varchar,
    title varchar NOT NULL,
    views integer
);

CREATE TABLE IF NOT EXISTS requests
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT requests_pk PRIMARY KEY,
    created timestamp,
    event_id bigint CONSTRAINT requests_events_id_fk REFERENCES events,
    requester_id bigint CONSTRAINT requests_users_id_fk REFERENCES users,
    status varchar
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    event_id bigint CONSTRAINT compilation_events_events_id_fk REFERENCES events,
    compilation_id bigint CONSTRAINT compilation_events_compilations_id_fk REFERENCES compilations,
    PRIMARY KEY (event_id, compilation_id)
);

