drop table if exists comment, category, users, event, request, compilation, compilation_events CASCADE;
-----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_name_category UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL CONSTRAINT uk_email_user UNIQUE,
    name varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EVENT (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    annotation varchar(1000),
    confirmed_requests bigint,
    created_on timestamp,
    description varchar(3000),
    event_date timestamp,
    lat REAL,
    lon REAL,
    paid boolean,
    participant_limit integer,
    published_on timestamp,
    request_moderation boolean,
    state text,
    title varchar(255),
    category_id bigint,
    user_id bigint,
    PRIMARY KEY (id),
    CONSTRAINT fk_event_category_id FOREIGN KEY (category_id) REFERENCES category,
    CONSTRAINT fk_event_user_id FOREIGN KEY (user_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS request (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created timestamp,
    status text,
    event_id bigint,
    requester_id bigint,
    PRIMARY KEY (id),
    CONSTRAINT fk_request_event_id FOREIGN KEY (event_id) REFERENCES EVENT,
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS compilation (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    pinned boolean,
    title varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id bigint NOT NULL,
    events_id bigint NOT NULL,
    PRIMARY KEY (compilation_id, events_id),
    CONSTRAINT fk_compilations_id FOREIGN KEY (compilation_id) REFERENCES compilation,
    CONSTRAINT fk_events_id FOREIGN KEY (events_id) REFERENCES EVENT,
    CONSTRAINT uk_events_id UNIQUE (events_id)
);

CREATE TABLE IF NOT EXISTS comment (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    event_id   bigint NOT NULL,
    author_id  bigint  NOT NULL,
    text    varchar(10000)  NOT NULL,
    state     text NOT NULL,
    created_on timestamp,
    PRIMARY KEY (id),
    CONSTRAINT fk_comment_event_id FOREIGN KEY (event_id) REFERENCES event,
    CONSTRAINT fk_comment_author_id FOREIGN KEY (author_id) REFERENCES users
);