drop table if exists endpoint_hit;
-----------------------------------------------------
CREATE TABLE IF NOT EXISTS endpoint_hit (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    app       varchar(255),
    ip        varchar(45),
    timestamp timestamp,
    uri       varchar(2048),
    PRIMARY KEY (id)
);