CREATE TABLE IF NOT EXISTS stats
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT stats_pk PRIMARY KEY,
    app varchar,
    uri varchar,
    ip varchar,
    timestamp timestamp
);