drop table if exists endpoint_hit;
-----------------------------------------------------
CREATE TABLE IF NOT EXISTS endpoint_hit (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    app       varchar(255),
    ip        varchar(255),
    timestamp timestamp,
    uri       varchar(255),
    PRIMARY KEY (id)
);